basePath: /api
host: localhost:8888
info:
  contact: {}
  description: A Tag service API in Go using Gin framework
  title: Tag Service API
  version: "1.0"
paths:
  /login:
    post:
      responses: {}
swagger: "2.0"
